language: node_js
node_js:
  - "9"

cache:
  yarn: true

sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_7c789783d536_key -iv $encrypted_7c789783d536_iv -in rsa.tar.enc -out ./rsa.tar -d
  - tar -xvf rsa.tar
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mv ./TXRsa ~/.ssh/id_rsa;
    fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    mv ./VTRsa ~/.ssh/id_rsa;
    fi
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 111.230.174.166\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host 45.76.52.33\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run lint
  - npm run lint:css
  - npm run build

after_success:
  - tar -jcf dist.tar.bz2 dist/*
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scp dist.tar.bz2 root@111.230.174.166:~/;
    ssh root@111.230.174.166 "sudo -i mv /root/dist.tar.bz2 ./gitcode/rent-manager/";
    ssh root@111.230.174.166 "sudo -i ./gitcode/rent-manager/autoFetch.sh $TRAVIS_BRANCH";
    fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    scp dist.tar.bz2 root@45.76.52.33:~/gitcode/rent-manager/;
    ssh root@45.76.52.33 "./gitcode/rent-manager/autoFetch.sh $TRAVIS_BRANCH";
    fi

addons:
  ssh_known_hosts:
    - 111.230.174.166
    - 45.76.52.33

branches:
  only:
    - master
    - test
