language: node_js
node_js:
  - 8.9.3

before_install:
  - openssl aes-256-cbc -K $encrypted_7c789783d536_key -iv $encrypted_7c789783d536_iv -in ssh-vultr2.ppk.enc -out ~/.ssh/ssh-vultr2.ppk -d
  - chmod 600 ~/.ssh/ssh-vultr2.ppk

script:
  - npm run build

after_success:
  - ssh root@45.76.52.33 "./gitcode/rentmanager/autoFetch"

addons:
  - ssh_known_hosts: 45.76.52.33

branches:
  only:
    - master
    - test
