language: node_js
node_js:
  - 8.9.3

before_install:
  - openssl aes-256-cbc -K $encrypted_7c789783d536_key -iv $encrypted_7c789783d536_iv -in rsa.tar.enc -out ./rsa.tar -d
  - tar -xvf rsa.tar
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    mv ./rsa/fn_id_rsa ~/.ssh/id_rsa;
    fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    mv ./rsa/sf_id_rsa ~/.ssh/id_rsa;
    fi
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 35.185.176.209\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host 45.76.52.33\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run build

after_success:
  - tar -jcf dist.tar.bz2 dist/*
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    scp dist.tar.bz2 rhinelkc@35.185.176.209:~/gitcode/rent-manager/;
    ssh rhinelkc@35.185.176.209 "sudo -i ./gitcode/rent-manager/autoFetch.sh $TRAVIS_BRANCH";
    fi
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    scp dist.tar.bz2 root@45.76.52.33:~/gitcode/rent-manager/;
    ssh root@45.76.52.33 "./gitcode/rent-manager/autoFetch.sh $TRAVIS_BRANCH";
    fi

addons:
  - ssh_known_hosts: 35.185.176.209
  - ssh_known_hosts: 45.76.52.33

branches:
  only:
    - master
    - test
